"""
Core event definitions for the backtesting engine.

This module defines the basic event types that are passed between
different components (data handlers, strategies, portfolio, execution)
via a central event queue in an event-driven architecture.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal, Optional


class Event:
    """
    Base class for all events in the backtesting engine.

    Each concrete event type should set the ``type`` attribute to a
    short uppercase string that uniquely identifies the event category
    (for example, ``'MARKET'`` or ``'ORDER'``).  The engine uses this
    attribute to route events to the appropriate components.
    """

    type: str


@dataclass(slots=True)
class MarketEvent(Event):
    """
    Indicates that new market data is available.

    The data handler emits a ``MarketEvent`` whenever it advances its
    internal time index and updates the latest bar(s) for all tracked
    symbols.  The event itself is intentionally lightweight; consumers
    are expected to query the data handler for the latest values.
    """

    type: str = field(init=False, default="MARKET")


SignalType = Literal["LONG", "SHORT", "EXIT"]


@dataclass(slots=True)
class SignalEvent(Event):
    """
    Encapsulates a trading signal generated by a strategy.

    Parameters
    ----------
    strategy_id:
        Identifier for the strategy instance that generated the signal.
    symbol:
        The asset symbol for which the signal is generated.
    datetime:
        Timestamp at which the signal was created.
    signal_type:
        One of ``'LONG'``, ``'SHORT'``, or ``'EXIT'``.
    strength:
        Optional scalar that allows a strategy to express the
        relative conviction in the signal, defaulting to 1.0.
    """

    strategy_id: str
    symbol: str
    datetime: datetime
    signal_type: SignalType
    strength: float = 1.0

    type: str = field(init=False, default="SIGNAL")


OrderType = Literal["MKT", "LMT"]
OrderDirection = Literal["BUY", "SELL"]


@dataclass(slots=True)
class OrderEvent(Event):
    """
    Represents an order to trade a given quantity of an asset.

    Parameters
    ----------
    symbol:
        The asset symbol to trade.
    order_type:
        The order type, typically ``'MKT'`` (market) or ``'LMT'`` (limit).
    quantity:
        Number of units to trade. Must be a positive integer.
    direction:
        Trade direction, either ``'BUY'`` or ``'SELL'``.
    """

    symbol: str
    order_type: OrderType
    quantity: int
    direction: OrderDirection

    type: str = field(init=False, default="ORDER")

    def print_order(self) -> None:
        """
        Print a human-readable representation of the order.

        This is primarily intended for debugging and logging.
        """

        print(
            f"Order: Symbol={self.symbol}, "
            f"Type={self.order_type}, "
            f"Quantity={self.quantity}, "
            f"Direction={self.direction}"
        )


FillDirection = OrderDirection


@dataclass(slots=True)
class FillEvent(Event):
    """
    Records the details of a filled order.

    Parameters
    ----------
    timeindex:
        The timestamp at which the fill occurred.
    symbol:
        The asset symbol that was traded.
    exchange:
        The venue on which the trade was executed.
    quantity:
        Number of units filled.
    direction:
        Direction of the fill, either ``'BUY'`` or ``'SELL'``.
    fill_cost:
        Total consideration for the fill, excluding commissions.
    commission:
        Explicit commission charged for the trade. If omitted, a basic
        simulated commission model will be applied on first access.
    """

    timeindex: datetime
    symbol: str
    exchange: str
    quantity: int
    direction: FillDirection
    fill_cost: float
    commission: Optional[float] = None

    type: str = field(init=False, default="FILL")

    def calculate_commission(
        self, minimum: float = 1.0, rate: float = 0.0005
    ) -> float:
       

        if self.commission is None:
            trade_value = abs(self.fill_cost)
            self.commission = max(minimum, rate * trade_value)
        return self.commission

